name: Test Plugins
on: workflow_dispatch
jobs:
  Clone-Repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox requests GitPython tqdm pandas pkginfo
      - name: List Files
        run: |
          ls ${{ github.workspace }}
      - name: Clone Plugin Repositories
        run: |
          python clone_all_repos.py
