name: Test Plugins
on: workflow_dispatch
jobs:
  Clone-Repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox requests GitPython tqdm pandas pkginfo
      - name: Clone Plugin Repositories
        run: |
          python clone_all_repos.py
      - name: Cache Repositories For Testing
        uses: actions/cache@v2
        with:
          path: ./repositories
          key: repositories
      - name: Save Repo Paths
        id: repo-paths
        run: echo "::set-output name=matrix::$(cat ./repo_pths.json)"
    outputs:
      matrix: ${{ steps.repo-paths.outputs.matrix }}
  Test-Repositories:
    needs: Clone-Repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ${{ fromJson(needs.Clone-Repositories.outputs.matrix) }}
    steps:
      - name: Restore Cached Repositories
        uses: actions/cache@v2
        with:
          path: ./repositories
          key: repositories
      - name: List Files
        working-directory: ${{ matrix.plugin }}
        run: |
          ls .
